Feature: DTS source language hover documentation

  Background:
    Given the language server is running
    And a DTS source language file is open

  Scenario: Hover on the DTS version directive returns focused documentation
    When hovering over the DTS version directive
    Then the hover text is exactly:
      """
      ## /dts-v1/; - DTS source language

      `/dts-v1/;` shall be present to identify the file as a version 1 DTS (dts files without this tag will be treated by dtc as being in the obsolete version 0, which uses a different format for integers in addition to other small but incompatible changes).
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on an include directive returns focused documentation
    When hovering over an include directive
    Then the hover text is exactly:
      """
      ## /include/ - DTS source language

      Other source files can be included from a DTS file. The name of include files should end with ".dtsi". Included files can in turn include additional files.

      ```
      /include/ "FILE"
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a memory reservation directive returns focused documentation
    When hovering over a memory reservation directive
    Then the hover text is exactly:
      """
      ## /memreserve/ - DTS source language

      Memory reservations are represented by lines in the form:

      ```
      /memreserve/ <address> <length>;
      ```

      Where `<address>` and `<length>` are 64-bit C-style integers.
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a delete-node directive returns focused documentation
    When hovering over a delete-node directive
    Then the hover text is exactly:
      """
      ## /delete-node/ - DTS source language

      Previously defined nodes may be deleted.

      ```
      /delete-node/ node-name;
      /delete-node/ &label;
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a delete-property directive returns focused documentation
    When hovering over a delete-property directive
    Then the hover text is exactly:
      """
      ## /delete-property/ - DTS source language

      Previously defined properties may be deleted.

      ```
      /delete-property/ property-name;
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a label definition returns focused documentation
    When hovering over a label definition
    Then the hover text is exactly:
      """
      ## Label definition - DTS source language

      Labels are created by appending a colon (`:`) to the label name.

      A label shall be between 1 to 31 characters in length, be composed only of the characters `0-9`, `a-z`, `A-Z`, and `_`, and must not start with a number.
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a label reference returns focused documentation
    When hovering over a label reference
    Then the hover text is exactly:
      """
      ## Label reference - DTS source language

      Phandle and path references can be automatically generated by referencing a label instead of explicitly specifying a phandle value or the full path to a node.

      References are created by prefixing the label name with an ampersand (`&`).
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a full path reference returns focused documentation
    When hovering over a full path reference
    Then the hover text is exactly:
      """
      ## Full path reference - DTS source language

      References may be `&` followed by a node's full path in braces.

      ```
      interrupt-parent = < &{/soc/interrupt-controller@40000} >;
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a cell array returns focused documentation
    When hovering over a cell array
    Then the hover text is exactly:
      """
      ## Cell array - DTS source language

      Arrays of cells are represented by angle brackets surrounding a space separated list of C-style integers.

      ```
      interrupts = <17 0xc>;
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a bytestring returns focused documentation
    When hovering over a bytestring
    Then the hover text is exactly:
      """
      ## Bytestring - DTS source language

      A bytestring is enclosed in square brackets `[ ]` with each byte represented by two hexadecimal digits. Spaces between each byte are optional.

      ```
      local-mac-address = [00 00 12 34 56 78];
      ```
      """
    And the hover title includes "DTS source language"

  Scenario: Hover on a string property value returns focused documentation
    When hovering over a string property value
    Then the hover text is exactly:
      """
      ## String value - DTS source language

      A null-terminated string value is represented using double quotes (the property value is considered to include the terminating NULL character).

      ```
      compatible = "simple-bus";
      ```
      """
    And the hover title includes "DTS source language"

